const $=s=>document.querySelector(s);let me=null,chart;
const I={home:'<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M9 22V12h6v10"/>',deposit:'<circle cx="12" cy="12" r="10"/><path d="M8 12l4 4 4-4M12 8v8"/>',withdraw:'<circle cx="12" cy="12" r="10"/><path d="M16 12l-4-4-4 4M12 16V8"/>',send:'<path d="M22 2L11 13M22 2l-7 20-4-9-9-4z"/>',list:'<path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/>',user:'<path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',briefcase:'<rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/>',users:'<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>'};
const ic=n=>`<svg class="ic" viewBox="0 0 24 24">${I[n]}</svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inr=n=>'₹'+Number(n).toLocaleString('en-IN',{minimumFractionDigits:2});
const dt=s=>new Date(s).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});
const api=async(u,m='GET',b)=>{const r=await fetch('/api'+u,{method:m,headers:{'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined});const d=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401&&me){alert('Session expired. Please log in again.');location.reload()}throw new Error(d.error||'Request failed')}return d};
const toast=(m,bad)=>{const t=$('#toast');t.textContent=m;t.className='show'+(bad?' bad':'');clearTimeout(t.h);t.h=setTimeout(()=>t.className='',3500)};
const ask=m=>new Promise(r=>{const o=$('#modal');o.hidden=false;o.innerHTML=`<div class="dlg" role="dialog"><p>${esc(m)}</p><div><button class="btn ghost" id="no">Cancel</button><button class="btn" id="yes">Confirm</button></div></div>`;$('#yes').focus();$('#yes').onclick=()=>{o.hidden=true;r(true)};$('#no').onclick=()=>{o.hidden=true;r(false)}});
const f=(id,l,t='text',x='')=>`<label>${l}<input name="${id}" id="${id}" type="${t}" ${x}></label>`;
const sel=(id,l,o)=>`<label>${l}<select name="${id}" id="${id}">${o.map(v=>`<option>${v}</option>`).join('')}</select></label>`;
const ERR='<p class="err" role="alert"></p>';
function bind(s,fn){const fm=$(s);fm.onsubmit=async e=>{e.preventDefault();const b=fm.querySelector('.btn'),er=fm.querySelector('.err');b.disabled=true;er.textContent='';try{await fn(Object.fromEntries(new FormData(fm)),fm)}catch(x){er.textContent=x.message}b.disabled=false}}

// ---------- Auth ----------
const AUTH={
login:()=>`<h2>Log in</h2><form id="fm">${f('id','Account number or email','text','required autocomplete="username"')}${f('pw','Password','password','required autocomplete="current-password"')}${ERR}<button class="btn">Log in</button></form><p class="alt"><a data-t="forgot">Forgot password?</a><a data-t="register">Open an account</a></p><p class="muted" style="margin-top:18px">Demo: rahul@example.com / Demo@1234 &nbsp; Admin: admin@bank.com / Admin@123</p>`,
register:()=>`<h2>Open an account</h2><form id="fm"><div class="g2">${f('name','Full name','text','required')}${f('dob','Date of birth','date','required')}${sel('gender','Gender',['Male','Female','Other'])}${f('mobile','Mobile number','tel','required maxlength="10"')}${f('email','Email','email','required')}${f('id_number','PAN or Aadhaar number','text','required maxlength="12"')}</div>${f('address','Address','text','required')}<div class="g2">${sel('type','Account type',['Savings','Current'])}${f('password','Password','password','required minlength="8"')}</div>${ERR}<button class="btn">Create account</button></form><p class="alt"><a data-t="login">Back to log in</a></p>`,
forgot:()=>`<h2>Reset password</h2><form id="fm">${f('email','Registered email','email','required')}${f('id_number','PAN or Aadhaar number','text','required')}${f('password','New password','password','required minlength="8"')}${ERR}<button class="btn">Reset password</button></form><p class="alt"><a data-t="login">Back to log in</a></p>`};
function showAuth(t='login'){$('#auth').hidden=false;$('#app').hidden=true;$('#authbox').innerHTML=AUTH[t]();
 if(t==='login')bind('#fm',async d=>{await api('/login','POST',{id:d.id,password:d.pw});me=await api('/me');enter()});
 if(t==='register')bind('#fm',async d=>{const r=await api('/register','POST',d);$('#authbox').innerHTML=`<h2>Request submitted</h2><p>Your account number is <b>${r.accountNo}</b>. You can log in once an admin approves it.</p><p class="alt"><a data-t="login">Go to log in</a></p>`});
 if(t==='forgot')bind('#fm',async d=>{await api('/forgot','POST',d);toast('Password updated. Log in with your new password.');showAuth()})}

// ---------- Shell ----------
const NAV={customer:[['dashboard','Dashboard','home'],['deposit','Deposit','deposit'],['withdraw','Withdraw','withdraw'],['transfer','Transfer','send'],['history','Transactions','list'],['profile','Profile','user'],['services','Services','briefcase']],admin:[['adash','Overview','home'],['acustomers','Customers','users'],['atx','Transactions','list']]};
function enter(){$('#auth').hidden=true;$('#app').hidden=false;const n=NAV[me.role];$('#nav').innerHTML=n.map(([k,l,i])=>`<a data-v="${k}" tabindex="0">${ic(i)}${l}</a>`).join('');go(n[0][0]);loadNotes()}
async function go(v){const n=NAV[me.role].find(x=>x[0]===v);document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('on',a.dataset.v===v));$('#title').textContent=n[1];$('#side').classList.remove('open');$('#view').innerHTML='<div class="load"></div>';try{await V[v]()}catch(e){$('#view').innerHTML=`<p class="err">${esc(e.message)}</p>`}}
async function loadNotes(){const n=await api('/notifications'),u=n.filter(x=>!x.is_read).length;$('#badge').hidden=!u;$('#badge').textContent=u;$('#notes').innerHTML=n.length?n.map(x=>`<div class="${x.is_read?'':'un'}">${esc(x.message)}<small>${dt(x.created_at)}</small></div>`).join(''):'<div>No notifications yet.</div>'}
document.addEventListener('click',async e=>{const t=e.target.closest('[data-t],[data-v],[data-go],[data-st]');
 if(!e.target.closest('.bell'))$('#notes').hidden=true;
 if(e.target.closest('#bell')){$('#notes').hidden=!$('#notes').hidden;if(!$('#notes').hidden){await api('/notifications/read','POST');$('#badge').hidden=true}return}
 if(e.target.closest('#menu'))$('#side').classList.toggle('open');
 if(e.target.closest('#logout')){await api('/logout','POST');me=null;showAuth()}
 if(!t)return;const d=t.dataset;
 if(d.t)showAuth(d.t);if(d.v)go(d.v);if(d.go)go(d.go);
 if(d.st&&await ask(`${d.st==='active'?'Approve or activate':d.st==='rejected'?'Reject':'Deactivate'} this account?`)){await api(`/admin/accounts/${d.id||t.dataset.id}/status`,'POST',{status:d.st});toast('Account updated');go($('#nav .on').dataset.v)}});

// ---------- Views ----------
const txTable=r=>r.length?`<div class="tw"><table><tr><th>ID</th><th>Date</th><th>Type</th><th>Amount</th><th>Balance</th></tr>${r.map(x=>`<tr><td>${x.txn_id}</td><td>${dt(x.created_at)}</td><td>${x.type}${x.counterparty?` <span class="muted">${x.direction==='Credit'?'from':'to'} ${x.counterparty}</span>`:''}</td><td class="${x.direction==='Credit'?'cr':'dr'}">${x.direction==='Credit'?'+':'−'}${inr(x.amount)}</td><td>${inr(x.balance_after)}</td></tr>`).join('')}</table></div>`:'<p class="muted">No transactions yet. Make a deposit to get started.</p>';
const money=(k,title)=>async()=>{$('#view').innerHTML=`<div class="card narrow"><h3>${title}</h3><p class="muted" style="margin-bottom:12px">Available balance: ${inr(me.balance)}</p><form id="fm">${f('amount','Amount (₹)','number','min="1" max="1000000" step="0.01" required')}${ERR}<button class="btn">${title}</button></form></div>`;
 bind('#fm',async d=>{if(!await ask(`${title} ${inr(d.amount)}?`))return;const r=await api('/'+k,'POST',{amount:d.amount});me.balance=r.balance;toast(`Done. Transaction ID ${r.txnId}`);loadNotes();go(k)})};
const V={
async dashboard(){const t=await api('/transactions');
 $('#view').innerHTML=`<section class="hero"><div><p>Welcome, ${esc(me.name.split(' ')[0])}</p><h2>${inr(me.balance)}</h2><small>Available balance</small></div><dl><dt>Account number</dt><dd>${me.account_no}</dd><dt>Account type</dt><dd>${me.type}</dd></dl></section>
 <div class="quick">${[['deposit','Deposit','deposit'],['withdraw','Withdraw','withdraw'],['transfer','Send money','send'],['history','Statement','list']].map(([v,l,i])=>`<button data-go="${v}">${ic(i)}${l}</button>`).join('')}</div>
 <div class="cols"><div class="card"><h3>Money in and out</h3><canvas id="ch" height="200"></canvas></div><div class="card"><h3>Recent transactions</h3>${txTable(t.slice(0,6))}</div></div>`;
 const m={};for(let i=5;i>=0;i--){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-i);m[d.toISOString().slice(0,7)]=[0,0]}
 t.forEach(x=>{const k=new Date(x.created_at).toISOString().slice(0,7);if(m[k])m[k][x.direction==='Credit'?0:1]+=x.amount});
 chart&&chart.destroy();chart=new Chart($('#ch'),{type:'bar',data:{labels:Object.keys(m),datasets:[{label:'Credited',data:Object.values(m).map(v=>v[0]),backgroundColor:'#1b7f4b'},{label:'Debited',data:Object.values(m).map(v=>v[1]),backgroundColor:'#B8893A'}]},options:{plugins:{legend:{position:'bottom'}}}})},
deposit:money('deposit','Deposit'),withdraw:money('withdraw','Withdraw'),
async transfer(){const b=await api('/beneficiaries');
 $('#view').innerHTML=`<div class="card narrow"><h3>Transfer money</h3><p class="muted" style="margin-bottom:12px">Available balance: ${inr(me.balance)}</p><form id="fm">${f('to','Receiver account number','text','required maxlength="12" list="bl" autocomplete="off"')}<datalist id="bl">${b.map(x=>`<option value="${x.benef_account_no}">${esc(x.nickname)}</option>`).join('')}</datalist><p id="rn" class="muted"></p>${f('amount','Amount (₹)','number','min="1" max="1000000" step="0.01" required')}${ERR}<button class="btn">Send money</button></form></div>`;
 $('#to').oninput=async e=>{const v=e.target.value,o=$('#rn');o.textContent='';if(v.length===12)try{o.textContent='Account holder: '+(await api('/lookup/'+v)).name}catch(x){o.textContent=x.message}};
 bind('#fm',async d=>{if(!await ask(`Send ${inr(d.amount)} to account ${d.to}?`))return;const r=await api('/transfer','POST',d);me.balance=r.balance;toast(`Transfer complete. ID ${r.txnId}`);loadNotes();go('transfer')})},
async history(){$('#view').innerHTML=`<div class="card"><div class="bar"><input id="q" placeholder="Search by ID or account" aria-label="Search"><select id="ty"><option value="">All types</option><option>Deposit</option><option>Withdrawal</option><option>Transfer</option></select><input id="fr" type="date" aria-label="From"><input id="to" type="date" aria-label="To"></div><div id="tb"></div></div>`;
 const run=async()=>{const p=new URLSearchParams({q:$('#q').value,type:$('#ty').value,from:$('#fr').value,to:$('#to').value});$('#tb').innerHTML=txTable(await api('/transactions?'+p))};
 ['q','ty','fr','to'].forEach(i=>$('#'+i).oninput=run);run()},
async profile(){me=await api('/me');
 $('#view').innerHTML=`<div class="cols"><div class="card"><h3>Your details</h3><p class="muted" style="margin-bottom:12px">${esc(me.name)} · ${me.account_no} · ${me.type} · ID ${esc(me.id_number)}</p><form id="f1">${f('email','Email','email',`required value="${esc(me.email)}"`)}${f('mobile','Mobile number','tel',`required maxlength="10" value="${esc(me.mobile)}"`)}${f('address','Address','text',`required value="${esc(me.address)}"`)}${ERR}<button class="btn">Save changes</button></form></div>
 <div class="card"><h3>Change password</h3><form id="f2">${f('current','Current password','password','required')}${f('next','New password','password','required minlength="8"')}${ERR}<button class="btn">Update password</button></form></div></div>`;
 bind('#f1',async d=>{await api('/profile','PUT',d);toast('Profile saved')});bind('#f2',async(d,fm)=>{await api('/password','PUT',d);fm.reset();toast('Password updated')})},
async services(){const S=[['Savings Account','3.5% p.a.','Zero-fee digital account for everyday saving. Minimum balance ₹1,000.'],['Current Account','0% interest','Built for businesses with unlimited transactions and overdraft options.'],['Fixed Deposit','6.5% to 7.25% p.a.','Lock funds for 1 to 5 years. Senior citizens earn 0.5% extra.'],['Home Loan','from 8.5% p.a.','Up to ₹5 crore for up to 30 years.'],['Personal Loan','from 10.99% p.a.','Up to ₹10 lakh, approved in 48 hours.'],['Customer support','1800-123-4567','support@meridianbank.example. Open Monday to Saturday, 9am to 6pm.']];
 $('#view').innerHTML=`<div class="svc">${S.map(s=>`<div class="card"><h3>${s[0]}</h3><b>${s[1]}</b><p class="muted">${s[2]}</p></div>`).join('')}</div>`},
async adash(){const [s,c]=await Promise.all([api('/admin/stats'),api('/admin/customers')]),p=c.filter(x=>x.status==='pending');
 $('#view').innerHTML=`<div class="stats">${[['Customers',s.customers],['Accounts',s.accounts],['Pending requests',s.pending],['Total deposits',inr(s.deposits)],['Total withdrawals',inr(s.withdrawals)]].map(x=>`<div class="card stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div><div class="card"><h3>Account requests</h3>${p.length?custTable(p):'<p class="muted">No pending requests.</p>'}</div>`},
async acustomers(){$('#view').innerHTML='<div class="card"><div class="bar"><input id="q" placeholder="Search name, email or account number" aria-label="Search customers"></div><div id="tb"></div></div>';
 const run=async()=>$('#tb').innerHTML=custTable(await api('/admin/customers?q='+encodeURIComponent($('#q').value)));$('#q').oninput=run;run()},
async atx(){const t=await api('/admin/transactions');$('#view').innerHTML=`<div class="card"><div class="tw"><table><tr><th>ID</th><th>Account</th><th>Date</th><th>Type</th><th>Amount</th></tr>${t.map(x=>`<tr><td>${x.txn_id}</td><td>${x.account_no}</td><td>${dt(x.created_at)}</td><td>${x.type}</td><td class="${x.direction==='Credit'?'cr':'dr'}">${x.direction==='Credit'?'+':'−'}${inr(x.amount)}</td></tr>`).join('')}</table></div></div>`}};
const custTable=r=>`<div class="tw"><table><tr><th>Account</th><th>Name</th><th>Email</th><th>Type</th><th>Balance</th><th>Status</th><th></th></tr>${r.map(x=>`<tr><td>${x.account_no}</td><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${x.type}</td><td>${inr(x.balance)}</td><td><span class="tag ${x.status}">${x.status}</span></td><td>${x.status==='pending'?`<button class="btn sm" data-id="${x.id}" data-st="active">Approve</button> <button class="btn sm red" data-id="${x.id}" data-st="rejected">Reject</button>`:x.status==='active'?`<button class="btn sm ghost" data-id="${x.id}" data-st="inactive">Deactivate</button>`:x.status==='inactive'?`<button class="btn sm" data-id="${x.id}" data-st="active">Activate</button>`:''}</td></tr>`).join('')}</table></div>`;
(async()=>{try{me=await api('/me');enter()}catch{me=null;showAuth()}})();
